(()=>{const trigger=document.querySelector('#changePassword')||(()=>{const b=document.createElement('button');b.id='changePassword';b.textContent='Сменить пароль';b.style.cssText='position:fixed;right:20px;bottom:20px;z-index:20;border:1px solid #d6e0da;background:white;border-radius:9px;padding:10px 14px;color:#236e53;cursor:pointer';document.body.appendChild(b);return b})();const wrap=document.createElement('div');wrap.style.cssText='display:none;position:fixed;inset:0;background:#16352b66;z-index:50;align-items:center;justify-content:center;padding:20px';wrap.innerHTML=`<form id="passwordChangeForm" style="width:min(420px,100%);background:#fff;border-radius:14px;padding:28px"><h2 style="margin-top:0">Смена пароля</h2><p style="color:#687083;font-size:12px">Новый пароль: минимум 10 символов, буквы и цифры.</p><label style="display:block;margin:12px 0;font-size:12px">Текущий пароль<input name="currentPassword" type="password" required style="display:block;width:100%;margin-top:6px;padding:10px"></label><label style="display:block;margin:12px 0;font-size:12px">Новый пароль<input name="newPassword" type="password" minlength="10" required style="display:block;width:100%;margin-top:6px;padding:10px"></label><div id="passwordChangeError" style="min-height:18px;color:#b4544e;font-size:11px"></div><div style="display:flex;justify-content:flex-end;gap:8px"><button type="button" id="passwordChangeCancel">Отмена</button><button type="submit">Сохранить</button></div></form>`;document.body.appendChild(wrap);trigger.addEventListener('click',()=>wrap.style.display='flex');wrap.querySelector('#passwordChangeCancel').onclick=()=>wrap.style.display='none';wrap.addEventListener('click',e=>{if(e.target===wrap)wrap.style.display='none'});wrap.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),r=await fetch('/api/account/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword:f.get('currentPassword'),newPassword:f.get('newPassword')})}),p=await r.json().catch(()=>({}));if(!r.ok){wrap.querySelector('#passwordChangeError').textContent=p.error||'Не удалось изменить пароль';return}alert('Пароль успешно изменен');e.target.reset();wrap.style.display='none'});})();
// Linking requires password confirmation and the same Google email.
async function refreshGoogleLinkStatus(){
 const [session,config]=await Promise.all([fetch('/api/session'),fetch('/api/auth/google/config')]);
 if(!session.ok)return; const googleEnabled=config.ok && (await config.json()).enabled;
 const account=await session.json(); document.querySelectorAll('[data-google-account-ui]').forEach(el=>el.remove());
 const messages={success:'Google успешно привязан. Теперь можно входить через Google.',email_mismatch:'Выбран другой Google-аккаунт. Для привязки выберите '+account.email,already_used:'Этот Google-аккаунт уже привязан к другому пользователю EduLink.',state:'Запрос привязки истёк или cookie потеряны. Повторите привязку в той же вкладке и браузере.',token:'Сервер не смог обменять код Google. Проверьте доступ к Google и настройки OAuth.',identity:'Не удалось проверить ответ Google. Повторите попытку; при повторении обратитесь к администратору.',cancelled:'Привязка отменена в Google.',link:'Привязка не завершена. Войдите заново по паролю и выберите Google-аккаунт с тем же email.',blocked:'Учётная запись заблокирована или неактивна.'};
 if(account.googleLinkResult){const message=document.createElement('div');message.setAttribute('data-google-account-ui','');message.setAttribute('role','alert');message.style.cssText='padding:16px;margin:12px;background:#fff4d9;border:1px solid #dcc99d;border-radius:10px;position:relative;z-index:30';message.textContent=messages[account.googleLinkResult]||'Google не удалось привязать. Повторите попытку.';const close=document.createElement('button');close.textContent='Закрыть';close.style.marginLeft='12px';close.onclick=()=>message.remove();message.append(close);(document.querySelector('main')||document.body).prepend(message);}
 const button=document.createElement('button');button.setAttribute('data-google-account-ui','');button.type='button';button.textContent='Привязать Google';button.className='ghost';
 button.style.cssText='position:fixed;right:20px;bottom:68px;z-index:20;padding:10px;background:white;border:1px solid #cad6ce;border-radius:9px;cursor:pointer';document.body.appendChild(button); button.textContent=account.googleLinked?'Google привязан':'Привязать Google'; button.disabled=account.googleLinked||!googleEnabled; button.title=account.googleLinked?'Учётная запись связана с Google':googleEnabled?'Google не привязан. Нажмите для привязки':'Google не привязан. Вход через Google не настроен'; const status=document.createElement('p');status.id='googleLinkStatus';status.setAttribute('data-google-account-ui','');status.setAttribute('role','status');status.textContent=account.googleLinked?'Google привязан':'Google не привязан';status.style.cssText='font-size:14px;color:#236e53;margin:12px 0'; const profile=document.querySelector('#teacherEmail')||document.querySelector('#studentEmail'); if(profile)profile.after(status); else {status.style.cssText+='position:fixed;right:20px;bottom:110px;background:white;padding:8px;border-radius:8px;z-index:20';document.body.appendChild(status);}
 const dialog=document.createElement('dialog');dialog.setAttribute('data-google-account-ui','');dialog.style.cssText='max-width:440px;border:1px solid #cad6ce;border-radius:14px;padding:24px';
 dialog.innerHTML='<form><h2>Привязать Google</h2><p>Подтвердите текущий пароль EduLink, затем выберите Google-аккаунт с тем же email.</p><p class="email"></p><label>Текущий пароль <input type="password" name="password" autocomplete="current-password" required></label><p role="alert"></p><button type="button">Отмена</button> <button type="submit">Продолжить с Google</button></form>';
 dialog.querySelector('.email').textContent=account.email;document.body.appendChild(dialog);
 button.onclick=()=>{dialog.querySelector('form').reset();dialog.querySelector('[role=alert]').textContent='';dialog.showModal();};
 dialog.querySelector('[type=button]').onclick=()=>dialog.close();
 dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const submit=dialog.querySelector('[type=submit]');submit.disabled=true;try{const r=await fetch('/api/auth/google/link',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:new FormData(e.target).get('password')})});const data=await r.json();if(!r.ok)throw Error(data.error||'Не удалось начать привязку');e.target.reset();location.href=data.url;}catch(err){dialog.querySelector('[role=alert]').textContent=err.message;}finally{submit.disabled=false;}};
}
refreshGoogleLinkStatus().catch(()=>{});
document.addEventListener('edulink:authenticated',()=>refreshGoogleLinkStatus().catch(()=>{}));
